NODE_LABEL = "ci.role.test&&hw.arch.x86&&sw.os.linux&&ubuntu&&sw.tool.docker" // need to double check specific platform requirements for the package jobs, "fpm?"

pipeline {
    agent { 
        label NODE_LABEL
    }
    stages {
        stage('Set up') {
            steps {
                setup()
            }
        }
        stage('Build and test package') {
            steps {
                dir('linuxNew') {
                    buildAndTest()
	            }
            }
        }
        // For now looks like upload is combined with build and tests
        stage('Upload') {
            steps {
                uploadArtifacts()
            }
        }
    }
}

def setup() {
    cleanWs()
    if (PLATFORM == "aarch64") {
        env.TESTCONTAINERS_RYUK_DISABLED=true
        env.TESTCONTAINERS_CHECKS_DISABLE=true
    }
    env._JAVA_OPTIONS="-Xmx4g"
    checkout scm: [$class: 'GitSCM',
            branches: [[name: "linux"]],
            extensions: [[$class: 'CleanBeforeCheckout']],
            userRemoteConfigs: [[url: "https://github.com/sophia-guo/installer"]]
    ]
}

def buildAndTest() {
    switch(JDK_SOURCE) {
        case "upstream":
            break;
        case "customized":
            break;
        default: //Adoptium API 
            break;
    }
    for (os in ["Debian", "RedHat", "Suse"]) {
        sh("./gradlew clean packageJdk${os} checkJdk${os} --parallel -PPRODUCT=${PRODUCT} -PPRODUCT_VERSION=${VERSION}")
    }
}

def uploadArtifacts() {
    echo "tests"
}
