@ECHO OFF

SET JDK_NAME=OpenJDK8
SET OPENJ9_VERSION=0.9.0

SET ARCH=x64

SET OPENJDK_VERSION=8.0.181+13
SET JDK_VERSION_NONSTANDARD=8u181b13
SET JDK_VERSION_NONSTANDARD2=8u181-b13
SET PACKAGE_TYPE=hotspot
REM OpenJDK8_x64_Win_jdk8u172-b11
REM OpenJDK8U-jdk_x64_windows_hotspot_8u181b13
"%ProgramFiles%\7-Zip\7z.exe" x "%JDK_NAME%U-jdk_%ARCH%_windows_hotspot_%JDK_VERSION_NONSTANDARD%.zip" -o"%JDK_NAME%\%PACKAGE_TYPE%\%ARCH%" "*" -r
move "%JDK_NAME%\%PACKAGE_TYPE%\%ARCH%\jdk%JDK_VERSION_NONSTANDARD2%" "%JDK_NAME%\%PACKAGE_TYPE%\%ARCH%\jdk-%OPENJDK_VERSION%"

SET OPENJDK_VERSION=8.0.181+13
SET JDK_VERSION_NONSTANDARD=8u181-b13
SET PACKAGE_TYPE=openj9
REM OpenJDK8-OPENJ9_x64_Windows_jdk8u181-b13_openj9-0.9.0
"%ProgramFiles%\7-Zip\7z.exe" x "%JDK_NAME%-OPENJ9_%ARCH%_Windows_jdk%JDK_VERSION_NONSTANDARD%_openj9-%OPENJ9_VERSION%.zip" -o"%JDK_NAME%\%PACKAGE_TYPE%\%ARCH%" "*" -r
move "%JDK_NAME%\%PACKAGE_TYPE%\%ARCH%\jdk%JDK_VERSION_NONSTANDARD%" "%JDK_NAME%\%PACKAGE_TYPE%\%ARCH%\jdk-%OPENJDK_VERSION%"


SET ARCH=
SET JDK_NAME=
SET JDK_VERSION_NONSTANDARD=
SET OPENJDK_VERSION=
SET OPENJ9_VERSION=
SET PACKAGE_TYPE=
